#ifndef __AMDPMBUS_H
#define __AMDPMBUS_H

#include <stdint.h>

#define PMBUS_PAGE						0x00
#define PMBUS_OPERATION					0x01
#define PMBUS_ON_OFF_CONFIG				0x02
#define PMBUS_CLEAR_FAULTS				0x03
#define PMBUS_PHASE						0x04

#define PMBUS_CAPABILITY				0x19
#define PMBUS_QUERY						0x1A

#define PMBUS_VOUT_MODE					0x20
#define PMBUS_VOUT_COMMAND				0x21
#define PMBUS_VOUT_TRIM					0x22
#define PMBUS_VOUT_CAL_OFFSET			0x23
#define PMBUS_VOUT_MAX					0x24
#define PMBUS_VOUT_MARGIN_HIGH			0x25
#define PMBUS_VOUT_MARGIN_LOW			0x26
#define PMBUS_VOUT_TRANSITION_RATE		0x27
#define PMBUS_VOUT_DROOP				0x28
#define PMBUS_VOUT_SCALE_LOOP			0x29
#define PMBUS_VOUT_SCALE_MONITOR		0x2A

#define PMBUS_COEFFICIENTS				0x30
#define PMBUS_POUT_MAX					0x31

#define PMBUS_FAN_CONFIG_12				0x3A
#define PMBUS_FAN_COMMAND_1				0x3B
#define PMBUS_FAN_COMMAND_2				0x3C
#define PMBUS_FAN_CONFIG_34				0x3D
#define PMBUS_FAN_COMMAND_3				0x3E
#define PMBUS_FAN_COMMAND_4				0x3F

#define PMBUS_VOUT_OV_FAULT_LIMIT		0x40
#define PMBUS_VOUT_OV_FAULT_RESPONSE	0x41
#define PMBUS_VOUT_OV_WARN_LIMIT		0x42
#define PMBUS_VOUT_UV_WARN_LIMIT		0x43
#define PMBUS_VOUT_UV_FAULT_LIMIT		0x44
#define PMBUS_VOUT_UV_FAULT_RESPONSE	0x45
#define PMBUS_IOUT_OC_FAULT_LIMIT		0x46
#define PMBUS_IOUT_OC_FAULT_RESPONSE	0x47
#define PMBUS_IOUT_OC_LV_FAULT_LIMIT	0x48
#define PMBUS_IOUT_OC_LV_FAULT_RESPONSE	0x49
#define PMBUS_IOUT_OC_WARN_LIMIT		0x4A
#define PMBUS_IOUT_UC_FAULT_LIMIT		0x4B
#define PMBUS_IOUT_UC_FAULT_RESPONSE	0x4C

#define PMBUS_OT_FAULT_LIMIT			0x4F
#define PMBUS_OT_FAULT_RESPONSE			0x50
#define PMBUS_OT_WARN_LIMIT				0x51
#define PMBUS_UT_WARN_LIMIT				0x52
#define PMBUS_UT_FAULT_LIMIT			0x53
#define PMBUS_UT_FAULT_RESPONSE			0x54
#define PMBUS_VIN_OV_FAULT_LIMIT		0x55
#define PMBUS_VIN_OV_FAULT_RESPONSE		0x56
#define PMBUS_VIN_OV_WARN_LIMIT			0x57
#define PMBUS_VIN_UV_WARN_LIMIT			0x58
#define PMBUS_VIN_UV_FAULT_LIMIT		0x59

#define PMBUS_IIN_OC_FAULT_LIMIT		0x5B
#define PMBUS_IIN_OC_WARN_LIMIT			0x5D

#define PMBUS_POUT_OP_FAULT_LIMIT		0x68
#define PMBUS_POUT_OP_WARN_LIMIT		0x6A
#define PMBUS_PIN_OP_WARN_LIMIT			0x6B

#define PMBUS_STATUS_BYTE				0x78
#define PMBUS_STATUS_WORD				0x79
#define PMBUS_STATUS_VOUT				0x7A
#define PMBUS_STATUS_IOUT				0x7B
#define PMBUS_STATUS_INPUT				0x7C
#define PMBUS_STATUS_TEMPERATURE		0x7D
#define PMBUS_STATUS_CML				0x7E
#define PMBUS_STATUS_OTHER				0x7F
#define PMBUS_STATUS_MFR_SPECIFIC		0x80
#define PMBUS_STATUS_FAN_12				0x81
#define PMBUS_STATUS_FAN_34				0x82

#define PMBUS_READ_VIN					0x88
#define PMBUS_READ_IIN					0x89
#define PMBUS_READ_VCAP					0x8A
#define PMBUS_READ_VOUT					0x8B
#define PMBUS_READ_IOUT					0x8C
#define PMBUS_READ_TEMPERATURE_1		0x8D
#define PMBUS_READ_TEMPERATURE_2		0x8E
#define PMBUS_READ_TEMPERATURE_3		0x8F
#define PMBUS_READ_FAN_SPEED_1			0x90
#define PMBUS_READ_FAN_SPEED_2			0x91
#define PMBUS_READ_FAN_SPEED_3			0x92
#define PMBUS_READ_FAN_SPEED_4			0x93
#define PMBUS_READ_DUTY_CYCLE			0x94
#define PMBUS_READ_FREQUENCY			0x95
#define PMBUS_READ_POUT					0x96
#define PMBUS_READ_PIN					0x97

#define PMBUS_REVISION					0x98
#define PMBUS_MFR_ID					0x99
#define PMBUS_MFR_MODEL					0x9A
#define PMBUS_MFR_REVISION				0x9B
#define PMBUS_MFR_LOCATION				0x9C
#define PMBUS_MFR_DATE					0x9D
#define PMBUS_MFR_SERIAL				0x9E

float PMBusDecodeLinearValue(uint16_t Input);
float PMBusDecodeLinearValueWithExponent(uint16_t mantissa, uint8_t exp);
uint16_t PMBusEncodeValueToLinearWithExponent(uint8_t RawExp, float Value);

#endif
